deployment:
  tasks:
    - echo "Activating Node.js environment..."
    - source /home/vibecekf/nodevenv/repositories/vibemotion/22/bin/activate && cd /home/vibecekf/repositories/vibemotion

    - echo "Installing dependencies..."
    - npm install

    - echo "Building React app..."
    - npm run build

    - echo "Deploying to public_html..."
    - export DEPLOYPATH=/home/vibecekf/public_html
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -r dist/* $DEPLOYPATH

    - echo "✅ Deployment complete."
